# Site settings
title: 			Vizabi
email: 			info@gapminder.org
description: 	"Vizabi is an open-source framework by Gapminder Foundation for creating maintainable charts and visualization tools. You can use it freely, adding Vizabi to your site or blog, developing new tools, or adding your own data."
baseurl: 		""
url: 			"http://vizabi.org"
github_username:  Gapminder/vizabi

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

#Blog
excerpt_separator: <!--more-->

# Assets
vizabi_version: release/v0.21.0
visabi_version_number: v0.22.0-8
download_address: "https://www.npmjs.com/package/vizabi"

pagination:
  enabled: true
  debug: true
  per_page: 3

menu:
  - title: Home
    url: /
  - title: Examples
    url: /examples/
  - title: Tutorials
    url: /tutorials/
    
assets:
  js_compressor:  	uglifier
  css_compressor: 	sass

exclude: [Gemfile, Gemfile.lock, README.md]

categories: [docs]

collections:
  docs:
    output: false
  examples:
    output: true
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:slug/
  tutorials:
    output: true
    permalink: /tutorials/:year/:month/:day/:slug/
  examples:
    output: true
    permalink: /examples/:slug:output_ext

gems: [jekyll-paginate-v2]