# Site settings
title: 			Vizabi
email: 			info@gapminder.org
description: 	"Vizabi is an open-source framework by Gapminder Foundation for creating maintainable charts and visualization tools. You can use it freely, adding Vizabi to your site or blog, developing new tools, or adding your own data."
baseurl: 		""
url: 			"http://vizabi.org"
github_username:  Gapminder/vizabi

# Build settings
markdown: kramdown

# Permalinks
permalink:           pretty
relative_permalinks: true

#Blog
highlighter:         pygments
excerpt_separator:   <!--more-->
paginate:			 3
paginate_path: 		 "/blog/:num/"

# Assets
vizabi_version:		release/v0.13.9-2
visabi_version_number: v0.13.9-2
download_address: "http://static.gapminderdev.org/vizabi/release/v0.13.9/download/vizabi.zip"

menu:
  - title: Home
    url: /
  - title: Examples
    url: /examples/
  - title: Docs
    url: /docs/
  - title: Blog
    url: /blog/

assets:
  js_compressor:  	uglifier
  css_compressor: 	sass

exclude: [Gemfile, Gemfile.lock, README.md]

categories: [docs]

collections:
  docs:
    output: false
  examples:
    output: true
